/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeemanagementsystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author hawba
 */
public class DepartmentForm extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement ps=null;
    ResultSet rs=null;
    
    public DepartmentForm() {
        initComponents();
        setSize(1080, 600);
        
        getLID();
        getDepartment();
        getTotalRows();
         
    }
    
    
 void getTotalRows(){
     
     int rows=tableDepartment.getRowCount();
     if(rows!=0){
         labelTotalRows.setText(rows+"");
     }
     
 }   
    
    
    
    
    
    void getLID(){
    MyConnection obj=new MyConnection();
    conn=obj.connectionDB();
    DefaultComboBoxModel comboModel=new DefaultComboBoxModel();
   
    try{
       String sql="select lid from location";
       ps=conn.prepareStatement(sql);
       rs =ps.executeQuery();
       
       while(rs.next()){
          String LID= rs.getString("lid");
          comboModel.addElement(LID);
       }
       
       cmbLID.setModel(comboModel);
       rs.close();
       conn.close();
       
        
    }catch(SQLException e){
        System.out.println("error in getLID:"+e);
    }
        
        
    }
    
 
    
    void getDepartment(){
    MyConnection obj=new MyConnection();
    conn=obj.connectionDB();  
    
    try{
     String sql="select * from department order by did";
     ps=conn.prepareStatement(sql);
     
     rs=ps.executeQuery();
     
     tableDepartment.setModel(DbUtils.resultSetToTableModel(rs));
     
     rs.close();
     conn.close();
        
    }catch(SQLException e){
        System.out.println("error in getDepartment:"+e);
    }
        
        
        
    }   
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtDID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbLID = new javax.swing.JComboBox<>();
        btnDelete = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDepartment = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        btnDisplayAll = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        labelTotalRows = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Department Form");
        setSize(new java.awt.Dimension(1080, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hawba\\OneDrive\\Documents\\NetBeansProjects\\EmployeeManagementSystem\\images\\d2.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(390, 10, 100, 110);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Department");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(510, 10, 320, 100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-1, 0, 1060, 130);

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DID:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 10, 40, 40);

        txtDID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(txtDID);
        txtDID.setBounds(60, 10, 210, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(10, 60, 50, 40);

        txtName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(txtName);
        txtName.setBounds(60, 60, 210, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LID:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 110, 40, 40);

        cmbLID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbLID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLIDActionPerformed(evt);
            }
        });
        jPanel3.add(cmbLID);
        cmbLID.setBounds(60, 110, 210, 40);

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btnDelete);
        btnDelete.setBounds(60, 280, 210, 40);

        btnInsert.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        jPanel3.add(btnInsert);
        btnInsert.setBounds(60, 180, 210, 40);

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel3.add(btnUpdate);
        btnUpdate.setBounds(60, 230, 210, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 140, 290, 450);

        tableDepartment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableDepartment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "DID", "Name", "LID"
            }
        ));
        tableDepartment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDepartmentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDepartment);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(300, 190, 760, 300);

        txtSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtSearch);
        txtSearch.setBounds(300, 140, 340, 40);

        btnDisplayAll.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDisplayAll.setText("Display All");
        btnDisplayAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayAllActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisplayAll);
        btnDisplayAll.setBounds(850, 140, 210, 40);

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch);
        btnSearch.setBounds(650, 140, 190, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Total Rows:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(310, 510, 100, 20);

        labelTotalRows.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTotalRows.setForeground(new java.awt.Color(255, 0, 0));
        labelTotalRows.setText("0");
        getContentPane().add(labelTotalRows);
        labelTotalRows.setBounds(420, 510, 170, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbLIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbLIDActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
       
     MyConnection obj=new MyConnection();
     conn=obj.connectionDB();
     
     String strDID=txtDID.getText();
     int did=Integer.parseInt(strDID);
     
     String name=txtName.getText();
     
     String strLID=cmbLID.getSelectedItem().toString();
     int lid=Integer.parseInt(strLID);
     
     
     
     try{
         String sql="insert into department(did,name,lid) values(?,?,?)";
         ps=conn.prepareCall(sql);
         ps.setInt(1,did);
         ps.setString(2, name);
         ps.setInt(3,lid);
         
         ps.executeUpdate();
         JOptionPane.showMessageDialog(null, "Insert Successfully!");
         
         getDepartment();
         getTotalRows();
         
         txtDID.setText("");
         txtName.setText("");
         cmbLID.setSelectedIndex(-1);
         
         conn.close();
         
         
         
         
     }catch(SQLException e){
         System.out.println("error in SQL Insert command"+e);
     }
        
        
        
        
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnDisplayAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayAllActionPerformed
        getDepartment();
    }//GEN-LAST:event_btnDisplayAllActionPerformed

    private void tableDepartmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDepartmentMouseClicked
        
    int rows= tableDepartment.getRowCount();
     if(rows!=0) {
        int selected_row=tableDepartment.getSelectedRow();
        String DID= tableDepartment.getValueAt(selected_row, 0).toString();
        String name= tableDepartment.getValueAt(selected_row, 1).toString();
        String LID= tableDepartment.getValueAt(selected_row, 2).toString();
        
        txtDID.setText(DID);
        txtName.setText(name);
        cmbLID.setSelectedItem(LID);
     }  
        
    }//GEN-LAST:event_tableDepartmentMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
     MyConnection obj=new MyConnection();
     conn=obj.connectionDB();
     String data=txtSearch.getText();
     
     try{
       String sql="select * from department where did LIKE ? " ;
       ps=conn.prepareStatement(sql);
       ps.setString(1,"%"+data+"%");  
       rs=ps.executeQuery();
       
       tableDepartment.setModel(DbUtils.resultSetToTableModel(rs));
       rs.close();
       conn.close();
         
     }catch(SQLException e){
      System.out.println("error in Search :"+e);   
    }
        
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        
    MyConnection obj=new MyConnection();
    conn= obj.connectionDB();
         
    String strDID=txtDID.getText();
    int DID=Integer.parseInt(strDID);
     
    String name=txtName.getText();
    
    String strLID=cmbLID.getSelectedItem().toString();
    int LID=Integer.parseInt(strLID);
    
         try{
            
             String sql="Update   department set  name=? , lid=? where did=?";
             ps=conn.prepareStatement(sql);
             ps.setString(1, name);
             ps.setInt(2,LID );
             ps.setInt(3,DID);
             
             ps.executeUpdate();
             JOptionPane.showMessageDialog(null, "update succesfully");
               
             txtDID.setText("");
             txtName.setText("");
             cmbLID.setSelectedIndex(-1);
            
             conn.close();    
            
         }catch(SQLException e){
              System.out.println("error in SQL Update command:"+e);
         }
          
        
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    MyConnection obj=new MyConnection();
    conn= obj.connectionDB();
         
    String strDID=txtDID.getText();
    int DID=Integer.parseInt(strDID);
   
         try{
           
             String sql="Delete from department where DID=?";
             ps=conn.prepareStatement(sql);
             ps.setInt(1, DID);
                        
             ps.executeUpdate();
             JOptionPane.showMessageDialog(null, "Delete succesfully");
             getDepartment();
             getTotalRows();
             
             txtDID.setText("");
             txtName.setText("");
             cmbLID.setSelectedIndex(-1);
            
             conn.close();    
            
         }catch(SQLException e){
              System.out.println("error in SQL Delete command:"+e);
         }
             
        
        
        
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDisplayAll;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbLID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTotalRows;
    private javax.swing.JTable tableDepartment;
    private javax.swing.JTextField txtDID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
