/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeemanagementsystem;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author hawba
 */
public class EmployeeForm extends javax.swing.JFrame {
    
    Connection conn;
    PreparedStatement ps=null;
    ResultSet rs=null;
   
    public EmployeeForm() {
        initComponents();
        
        setSize(1080, 600);
        getDID();
        getEmployee();
     
        
    }
    
    
void getTotalRows(){
   int rows= tableEmployee.getRowCount();
   labelToalRows.setText(rows+"");
    
}
 
void getSummationSalary(){
       int rows= tableEmployee.getRowCount();
       double sum=0;
       for(int i=0;i<rows;i++){
       
       sum=sum+Double.parseDouble(tableEmployee.getValueAt(i, 3).toString());
    
       }
       
       labelSummationSalaries.setText(sum+"");
       
    
}

    
    
    
    
    
    
    
    
 void getDID(){
 
   MyConnection obj=new MyConnection();
   conn= obj.connectionDB();  
  
   DefaultComboBoxModel comboModel=new DefaultComboBoxModel();
   
   try{
       String sql="select did from department";
       ps=conn.prepareStatement(sql);
       rs= ps.executeQuery();
       
       while(rs.next()){
          String did= rs.getString("did");
          comboModel.addElement(did);
       }
       
       cmbDID.setModel(comboModel);
       
       
   }catch(SQLException e){
       System.out.println("Error in getDID :"+e);
   }
   
   
   
     
     
 }   
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtEID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFullname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbGender = new javax.swing.JComboBox<>();
        txtSalary = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtStartWork = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        cmbDID = new javax.swing.JComboBox<>();
        btnDelete = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEmployee = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnDisplayALL = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        labelToalRows = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelSummationSalaries = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Employee Form");
        setSize(new java.awt.Dimension(1080, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hawba\\OneDrive\\Documents\\NetBeansProjects\\EmployeeManagementSystem\\images\\emp.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(340, 0, 120, 90);

        jLabel2.setBackground(new java.awt.Color(255, 102, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Employee");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(470, 10, 260, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 11, 1050, 90);

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EID:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 20, 60, 30);

        txtEID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txtEID);
        txtEID.setBounds(120, 20, 230, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gender:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 100, 90, 30);

        txtFullname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txtFullname);
        txtFullname.setBounds(120, 60, 230, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FullName:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 60, 100, 30);

        cmbGender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel2.add(cmbGender);
        cmbGender.setBounds(120, 100, 230, 30);

        txtSalary.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txtSalary);
        txtSalary.setBounds(120, 140, 230, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DID:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 220, 100, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Salary:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 140, 90, 30);

        txtStartWork.setDateFormatString("dd/MM/yyyy");
        txtStartWork.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txtStartWork);
        txtStartWork.setBounds(120, 180, 230, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Start_work:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 180, 110, 30);

        cmbDID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(cmbDID);
        cmbDID.setBounds(120, 220, 230, 30);

        btnDelete.setBackground(new java.awt.Color(153, 255, 153));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete);
        btnDelete.setBounds(120, 390, 230, 40);

        btnInsert.setBackground(new java.awt.Color(153, 255, 153));
        btnInsert.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        jPanel2.add(btnInsert);
        btnInsert.setBounds(120, 270, 230, 40);

        btnUpdate.setBackground(new java.awt.Color(153, 255, 153));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate);
        btnUpdate.setBounds(120, 330, 230, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 110, 430, 460);

        tableEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tableEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "EID", "Full Name", "Gender", "Salary", "Start Work", "DID"
            }
        ));
        tableEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEmployeeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableEmployee);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(450, 150, 610, 330);

        txtSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtSearch);
        txtSearch.setBounds(450, 110, 250, 30);

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch);
        btnSearch.setBounds(710, 110, 170, 30);

        btnDisplayALL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDisplayALL.setText("Display All");
        btnDisplayALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayALLActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisplayALL);
        btnDisplayALL.setBounds(890, 110, 170, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 255));
        jLabel9.setText("Total Rows:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(450, 500, 110, 40);

        labelToalRows.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelToalRows.setForeground(new java.awt.Color(204, 0, 51));
        labelToalRows.setText("0");
        getContentPane().add(labelToalRows);
        labelToalRows.setBounds(560, 500, 170, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 255));
        jLabel10.setText("Summation of Salaries:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(740, 500, 210, 40);

        labelSummationSalaries.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelSummationSalaries.setForeground(new java.awt.Color(204, 0, 51));
        labelSummationSalaries.setText("0");
        getContentPane().add(labelSummationSalaries);
        labelSummationSalaries.setBounds(950, 500, 120, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
       
    MyConnection obj=new MyConnection();
    conn= obj.connectionDB(); 
    
    String strEID=txtEID.getText();
    int eid=Integer.parseInt(strEID);
    
    String fullname=txtFullname.getText();
    String gender=cmbGender.getSelectedItem().toString();
  
    String strSalary=txtSalary.getText();
    double salary=Double.parseDouble(strSalary);
    
    Date startWork=new Date(txtStartWork.getDate().getTime());
    
    String strDID=cmbDID.getSelectedItem().toString();
    int did=Integer.parseInt(strDID);
    
    
    try{
      String sql ="insert into Employee (eid,fullname,gender,salary,start_work,did)"
              + "values (?,?,?,?,?,?)";
      
      ps=conn.prepareStatement(sql);
      ps.setInt(1,eid);
      ps.setString(2,fullname);
      ps.setString(3,gender);
      ps.setDouble(4, salary);
      ps.setDate(5, startWork);
      ps.setInt(6, did);
      
      ps.executeUpdate();
      JOptionPane.showMessageDialog(null, "Insert successfully!");
    
      getEmployee();
      
      txtEID.setText("");
      txtFullname.setText("");
      cmbGender.setSelectedIndex(-1);
      txtSalary.setText("");
      txtStartWork.setDate(null);
      cmbDID.setSelectedIndex(-1);
      
      
      conn.close();
      
     
    }catch(SQLException e){
        System.out.println("Error in SQL Insert command from employee"+e);
    }

        
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnDisplayALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayALLActionPerformed
        
        getEmployee();
    }//GEN-LAST:event_btnDisplayALLActionPerformed

    private void tableEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEmployeeMouseClicked
     
     int rows=-tableEmployee.getRowCount();
        if(rows!=0){
            int selected_row=tableEmployee.getSelectedRow();
            String eid=tableEmployee.getValueAt(selected_row, 0).toString();
            String fname=tableEmployee.getValueAt(selected_row, 1).toString();
            String gender=tableEmployee.getValueAt(selected_row, 2).toString();
            String salary=tableEmployee.getValueAt(selected_row, 3).toString();
            Date startWork=(Date) tableEmployee.getValueAt(selected_row, 4);
            String did=tableEmployee.getValueAt(selected_row, 5).toString();
            
            
            txtEID.setText(eid);
            txtFullname.setText(fname);
            cmbGender.setSelectedItem(gender);
            txtSalary.setText(salary);
            txtStartWork.setDate(startWork);
            cmbDID.setSelectedItem(did);
            
            
            
        }
        
    }//GEN-LAST:event_tableEmployeeMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
       
    MyConnection obj=new MyConnection();
    conn= obj.connectionDB(); 
     
    String data=txtSearch.getText();
    
     try{
         String sql="select * from employee where eid LIKE ? ";
         ps=conn.prepareStatement(sql);
         ps.setString(1,"%"+data+"%");
         
         rs=ps.executeQuery();
         
         tableEmployee.setModel(DbUtils.resultSetToTableModel(rs));
         
         conn.close();
         
     }catch(SQLException e){
         System.out.println("error in search :"+e);
     }   
        
        
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
     MyConnection obj=new MyConnection();
     conn= obj.connectionDB(); 
     
     String strEid=txtEID.getText().toString();
     int eid=Integer.parseInt(strEid);
     
     String fullname=txtFullname.getText();
     String gender=cmbGender.getSelectedItem().toString();
     
     String strSalary=txtSalary.getText();
     double salary=Double.parseDouble(strSalary);
     
     Date startWork=new Date(txtStartWork.getDate().getTime());
     
     String strDID=cmbDID.getSelectedItem().toString();
     int did=Integer.parseInt(strDID);
     
     
     
     try{
        String sql="update Employee set fullname=? , gender=? , salary=?,start_work=? ,did=? "
                + "where eid=?";
         ps=conn.prepareStatement(sql);
         ps.setString(1,fullname);
         ps.setString(2, gender);
         ps.setDouble(3, salary);
         ps.setDate(4, startWork);
         ps.setInt(5, did);
         ps.setInt(6,eid);
         
         ps.executeUpdate();
         JOptionPane.showMessageDialog(null, "Updated successfully!!");
         getEmployee();
         
         txtEID.setText("");
         txtFullname.setText("");
         txtSalary.setText("");
         txtStartWork.setDate(null);
         cmbGender.setSelectedIndex(-1);
         cmbDID.setSelectedIndex(-1);

         conn.close();
     
         
         
     }catch(SQLException e){
         System.out.println("error in Update employee :"+e);
     }     
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
     MyConnection obj=new MyConnection();
     conn= obj.connectionDB(); 
   
     String strEID=txtEID.getText();
     int eid=Integer.parseInt(strEID);
     
     try{
         String sql="delete from employee where eid=? ";
      
         ps=conn.prepareStatement(sql);
         ps.setInt(1,eid);
         
         ps.executeUpdate();
         JOptionPane.showMessageDialog(null, "Deleted Successfully!");
        
         getEmployee();
        
         txtEID.setText("");
         txtFullname.setText("");
         cmbGender.setSelectedIndex(-1);
         cmbDID.setSelectedIndex(-1);
         txtStartWork.setDate(null);
         txtSalary.setText("");
                 
         
         conn.close();
         
     }catch(SQLException e){
         System.out.println("error in delete :"+e);
     }   
     
     
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed


    
    void getEmployee(){
     MyConnection obj=new MyConnection();
     conn= obj.connectionDB(); 
     
     try{
         String sql="select * from employee order by eid";
         ps=conn.prepareStatement(sql);
         rs=ps.executeQuery();
         
         tableEmployee.setModel(DbUtils.resultSetToTableModel(rs));
         getTotalRows();
         getSummationSalary();
         
         conn.close();
         
     }catch(SQLException e){
         System.out.println("error in getEmployee :"+e);
     }
     
        
        
    }
 
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDisplayALL;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbDID;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelSummationSalaries;
    private javax.swing.JLabel labelToalRows;
    private javax.swing.JTable tableEmployee;
    private javax.swing.JTextField txtEID;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtSearch;
    private com.toedter.calendar.JDateChooser txtStartWork;
    // End of variables declaration//GEN-END:variables
}
