/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeemanagementsystem;

import java.io.InputStream;
import java.sql.Connection;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;




/**
 *
 * @author hawba
 */
public class Report extends javax.swing.JFrame {

  Connection conn=null;
  
    public Report() {
        initComponents();
        setSize(1000, 600);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLocationReport = new javax.swing.JButton();
        btnDepartment = new javax.swing.JButton();
        btnEmployeeReport = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnReport1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnReportByEID = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnReportCountEmployee = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnChartReport = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnReportTable = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Report");
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(null);

        btnLocationReport.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLocationReport.setText("Location Report");
        btnLocationReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocationReportActionPerformed(evt);
            }
        });
        getContentPane().add(btnLocationReport);
        btnLocationReport.setBounds(370, 20, 420, 60);

        btnDepartment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDepartment.setText("Department Report");
        btnDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartmentActionPerformed(evt);
            }
        });
        getContentPane().add(btnDepartment);
        btnDepartment.setBounds(370, 90, 420, 60);

        btnEmployeeReport.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEmployeeReport.setText("Employee Report");
        btnEmployeeReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeReportActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmployeeReport);
        btnEmployeeReport.setBounds(370, 160, 420, 60);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Generate a report with using Table:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 450, 480, 60);

        btnReport1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReport1.setText("Get");
        btnReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReport1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnReport1);
        btnReport1.setBounds(530, 240, 260, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Get  those employees who are working in 'SUL' city.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 230, 480, 60);
        getContentPane().add(txtSearch);
        txtSearch.setBounds(270, 300, 230, 40);

        btnReportByEID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReportByEID.setText("Get");
        btnReportByEID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportByEIDActionPerformed(evt);
            }
        });
        getContentPane().add(btnReportByEID);
        btnReportByEID.setBounds(530, 300, 260, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Generate a report by EID:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 290, 240, 60);

        btnReportCountEmployee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReportCountEmployee.setText("Get");
        btnReportCountEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportCountEmployeeActionPerformed(evt);
            }
        });
        getContentPane().add(btnReportCountEmployee);
        btnReportCountEmployee.setBounds(530, 350, 260, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Get the number of employees for each Department:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 340, 480, 60);

        btnChartReport.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnChartReport.setText("Get");
        btnChartReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChartReportActionPerformed(evt);
            }
        });
        getContentPane().add(btnChartReport);
        btnChartReport.setBounds(530, 410, 260, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Generate Chart Report for employees salary:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 390, 480, 60);

        btnReportTable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReportTable.setText("Get");
        btnReportTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportTableActionPerformed(evt);
            }
        });
        getContentPane().add(btnReportTable);
        btnReportTable.setBounds(530, 470, 260, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnLocationReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocationReportActionPerformed
    
     MyConnection obj=new MyConnection();
     conn=obj.connectionDB();
     
     try{
      
      JasperReport jr=null;
      InputStream path=this.getClass().getResourceAsStream("Report/LocationReport.jrxml");
      
      JasperDesign jd=JRXmlLoader.load(path);
      
      String sql="Select * from Location";
      
      JRDesignQuery query=new JRDesignQuery();
      query.setText(sql);
         
      jd.setQuery(query);
      
      jr=JasperCompileManager.compileReport(jd);
      
      JasperPrint jsPrint=null;
      jsPrint=JasperFillManager.fillReport(jr, null,conn);
      JasperViewer.viewReport(jsPrint, false);
         
     }catch(JRException e){
         System.out.println("error location report:"+e);
     }
     
    
        
        
    }//GEN-LAST:event_btnLocationReportActionPerformed

    private void btnDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartmentActionPerformed
   
     MyConnection obj=new MyConnection();
     conn=obj.connectionDB();
     
     try{
      
      JasperReport jr=null;
      InputStream path=this.getClass().getResourceAsStream("Report/DepartmentReport.jrxml");
      
      JasperDesign jd=JRXmlLoader.load(path);
      
      String sql="Select * from department";
      
      JRDesignQuery query=new JRDesignQuery();
      query.setText(sql);
         
      jd.setQuery(query);
      
      jr=JasperCompileManager.compileReport(jd);
      
      JasperPrint jsPrint=null;
      jsPrint=JasperFillManager.fillReport(jr, null,conn);
      JasperViewer.viewReport(jsPrint, false);
         
     }catch(JRException e){
         System.out.println("error department report:"+e);
     }
        
        
        
        
        
    }//GEN-LAST:event_btnDepartmentActionPerformed

    private void btnEmployeeReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeReportActionPerformed
        
     MyConnection obj=new MyConnection();
     conn=obj.connectionDB();
     
     try{
      
      JasperReport jr=null;
      InputStream path=this.getClass().getResourceAsStream("Report/EmployeeReport.jrxml");
      
      JasperDesign jd=JRXmlLoader.load(path);
      
      String sql="Select * from employee";
      
      JRDesignQuery query=new JRDesignQuery();
      query.setText(sql);
         
      jd.setQuery(query);
      
      jr=JasperCompileManager.compileReport(jd);
      
      JasperPrint jsPrint=null;
      jsPrint=JasperFillManager.fillReport(jr, null,conn);
      JasperViewer.viewReport(jsPrint, false);
         
     }catch(JRException e){
         System.out.println("error department report:"+e);
     }  
        
        
    }//GEN-LAST:event_btnEmployeeReportActionPerformed

    private void btnReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReport1ActionPerformed
        
     MyConnection obj=new MyConnection();
     conn=obj.connectionDB();
     
     String city="Sul";
     
     try{
      
      JasperReport jr=null;
      InputStream path=this.getClass().getResourceAsStream("Report/Report1.jrxml");
      
      JasperDesign jd=JRXmlLoader.load(path);
      
      String sql="Select e.eid,e.fullname,D.name,L.city from Employee E "
              + " inner join Department D on E.did=D.did inner join Location L "
              + " on D.lid=L.lid and L.city='"+city+"'  "
              + " order by e.eid ";
      
      JRDesignQuery query=new JRDesignQuery();
      query.setText(sql);
         
      jd.setQuery(query);
      
      jr=JasperCompileManager.compileReport(jd);
      
      JasperPrint jsPrint=null;
      jsPrint=JasperFillManager.fillReport(jr, null,conn);
      JasperViewer.viewReport(jsPrint, false);
         
     }catch(JRException e){
         System.out.println("error Report1 report:"+e);
     }  
            
        
        
        
    }//GEN-LAST:event_btnReport1ActionPerformed

    private void btnReportByEIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportByEIDActionPerformed
     MyConnection obj=new MyConnection();
     conn=obj.connectionDB();
     String strEID=txtSearch.getText();
     int EID=Integer.parseInt(strEID);
     
     try{
      
      JasperReport jr=null;
      InputStream path=this.getClass().getResourceAsStream("Report/ReportByEID.jrxml");
      
      JasperDesign jd=JRXmlLoader.load(path);
      
      String sql="Select * from Employee E inner join Department D "
              + " on E.did=D.did  inner join Location L "
              + " on L.LID=D.LID and E.EID='"+EID+"' ";
      
      JRDesignQuery query=new JRDesignQuery();
      query.setText(sql);
         
      jd.setQuery(query);
      
      jr=JasperCompileManager.compileReport(jd);
      
      JasperPrint jsPrint=null;
      jsPrint=JasperFillManager.fillReport(jr, null,conn);
      JasperViewer.viewReport(jsPrint, false);
         
     }catch(JRException e){
         System.out.println("error ReportByEID report:"+e);
     }  
    }//GEN-LAST:event_btnReportByEIDActionPerformed

    private void btnReportCountEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportCountEmployeeActionPerformed
     MyConnection obj=new MyConnection();
     conn=obj.connectionDB();
     
    
     
     try{
      
      JasperReport jr=null;
      InputStream path=this.getClass().getResourceAsStream("Report/ReportCountEmployee.jrxml");
      
      JasperDesign jd=JRXmlLoader.load(path);
      
      String sql="Select did,count(*) from employee group by did ";
      
      JRDesignQuery query=new JRDesignQuery();
      query.setText(sql);
         
      jd.setQuery(query);
      
      jr=JasperCompileManager.compileReport(jd);
      
      JasperPrint jsPrint=null;
      jsPrint=JasperFillManager.fillReport(jr, null,conn);
      JasperViewer.viewReport(jsPrint, false);
         
     }catch(JRException e){
         System.out.println("error ReportCiuntEpmloyee:"+e);
     }  
     
    }//GEN-LAST:event_btnReportCountEmployeeActionPerformed

    private void btnChartReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChartReportActionPerformed
       
     MyConnection obj=new MyConnection();
     conn=obj.connectionDB();
     
     try{
      
      JasperReport jr=null;
      InputStream path=this.getClass().getResourceAsStream("Report/ReportChart.jrxml");
      
      JasperDesign jd=JRXmlLoader.load(path);
      
      String sql="Select * from Employee ";
      
      JRDesignQuery query=new JRDesignQuery();
      query.setText(sql);
         
      jd.setQuery(query);
      
      jr=JasperCompileManager.compileReport(jd);
      
      JasperPrint jsPrint=null;
      jsPrint=JasperFillManager.fillReport(jr, null,conn);
      JasperViewer.viewReport(jsPrint, false);
         
     }catch(JRException e){
         System.out.println("error ReportChart:"+e);
     }  
       
        
        
    }//GEN-LAST:event_btnChartReportActionPerformed

    private void btnReportTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportTableActionPerformed
        
       MyConnection obj=new MyConnection();
     conn=obj.connectionDB();
     
     try{
      
      JasperReport jr=null;
      InputStream path=this.getClass().getResourceAsStream("Report/ReportTable.jrxml");
      
      JasperDesign jd=JRXmlLoader.load(path);
      
      String sql="Select * from Employee ";
      
      JRDesignQuery query=new JRDesignQuery();
      query.setText(sql);
         
      jd.setQuery(query);
      
      jr=JasperCompileManager.compileReport(jd);
      
      JasperPrint jsPrint=null;
      jsPrint=JasperFillManager.fillReport(jr, null,conn);
      JasperViewer.viewReport(jsPrint, false);
         
     }catch(JRException e){
         System.out.println("error ReportTable:"+e);
     }  
         
        
        
        
    }//GEN-LAST:event_btnReportTableActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChartReport;
    private javax.swing.JButton btnDepartment;
    private javax.swing.JButton btnEmployeeReport;
    private javax.swing.JButton btnLocationReport;
    private javax.swing.JButton btnReport1;
    private javax.swing.JButton btnReportByEID;
    private javax.swing.JButton btnReportCountEmployee;
    private javax.swing.JButton btnReportTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
